# 공통 config
# 3307, admin, port 주의
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    refresh:
      enable: false
  instance:
    nonSecurePort: ${server.port}
server:
  port: 0
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  cloud:
    bus:
      enabled: true
      id: ${spring.application.name}:${server.port}:${random.value}
